# Generated by Django 4.2 on 2026-03-14 19:31

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('returning_users', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('emergency_detections', models.IntegerField(default=0)),
                ('location_shares', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('top_diseases', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emergency_detected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('common_symptoms', models.TextField(help_text='Comma-separated list of symptoms')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Immediate Emergency'), ('URGENT', 'Seek Care Within Hours'), ('CAUTION', 'Monitor Carefully')], max_length=20)),
                ('response_message', models.TextField(help_text='What to tell the user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('age_group', models.CharField(choices=[('0-12', 'Child (0-12)'), ('13-17', 'Teen (13-17)'), ('18-35', 'Young Adult (18-35)'), ('36-50', 'Adult (36-50)'), ('51+', 'Senior (51+)'), ('unknown', 'Prefer not to say')], default='unknown', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Prefer not to say')], default='unknown', max_length=20)),
                ('location', models.CharField(blank=True, help_text='City/Region in Kenya', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('total_sessions', models.IntegerField(default=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField()),
                ('raw_input', models.TextField()),
                ('matched_diseases', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to='chatbot.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alternative_names', models.TextField(blank=True, help_text='Common variations')),
                ('diseases', models.ManyToManyField(blank=True, related_name='symptoms', to='chatbot.disease')),
            ],
        ),
        migrations.CreateModel(
            name='FirstAidProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('steps', models.TextField(help_text='Step-by-step instructions')),
                ('warning_notes', models.TextField(blank=True)),
                ('when_to_seek_help', models.TextField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_aid_procedures', to='chatbot.disease')),
            ],
        ),
        migrations.CreateModel(
            name='FirstAidFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('response_given', models.TextField()),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 - Not Helpful'), (2, '2 - Somewhat Helpful'), (3, '3 - Helpful'), (4, '4 - Very Helpful'), (5, '5 - Extremely Helpful')], null=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('symptom_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.symptomlog')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_keywords', models.JSONField()),
                ('severity', models.CharField(max_length=20)),
                ('raw_input', models.TextField()),
                ('location_shared', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('nearby_hospitals_shown', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_logs', to='chatbot.userprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['name'], name='chatbot_dis_name_ff4050_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chatbot_dis_search__130f91_gin'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='chatbot.userprofile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chatbot.userprofile'),
        ),
        migrations.AddIndex(
            model_name='chatanalytics',
            index=models.Index(fields=['date'], name='chatbot_cha_date_1d8b35_idx'),
        ),
    ]
