# Generated by Django 4.2 on 2026-04-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatanalytics',
            name='avg_messages_per_user',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatanalytics',
            name='emergency_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatanalytics',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatanalytics',
            name='error_occurred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatanalytics',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatanalytics',
            name='peak_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='chatanalytics',
            name='rating_distribution',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='chatanalytics',
            name='total_feedback',
            field=models.IntegerField(default=0),
        ),
    ]
